# Generated by Django 4.2.7 on 2024-02-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emai',
            new_name='email',
        ),
    ]
