# Generated by Django 4.2.7 on 2024-02-10 13:45

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_emai_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(verbose_name=builtins.max),
        ),
    ]
