# Generated by Django 4.2.7 on 2024-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_address_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(max_length=50),
        ),
    ]
