# Generated by Django 4.2.7 on 2024-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
    ]
